In [7]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import  RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [4]:
data = {
    "age": [18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
            28, 29, 30, 31, 32, 33, 34, 35, 36, 37],

    "study_hours": [1, 2, 2, 3, 4, 5, 5, 6, 7, 7,
                    8, 8, 9, 9, 10, 10, 11, 11, 12, 12],

    "pass": [0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
             1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)

print(df)


    age  study_hours  pass
0    18            1     0
1    19            2     0
2    20            2     0
3    21            3     0
4    22            4     1
5    23            5     1
6    24            5     1
7    25            6     1
8    26            7     1
9    27            7     1
10   28            8     1
11   29            8     1
12   30            9     1
13   31            9     1
14   32           10     1
15   33           10     1
16   34           11     1
17   35           11     1
18   36           12     1
19   37           12     1


In [8]:
x = df[["age","study_hours"]]
y = df["pass"]

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [48]:
scaler = StandardScaler()
xtrainscaled = scaler.fit_transform(x_train)
xtestscaled = scaler.transform(x_test)
print(xtrainscaled)
print(xtestscaled)

[[-0.35612994 -0.12598816]
 [-0.94558639 -0.797925  ]
 [ 0.23332651  0.20998026]
 [-1.33855735 -1.46986184]
 [ 1.60872489  1.55385394]
 [ 1.21575393  1.21788552]
 [ 0.62629748  0.54594868]
 [-1.53504284 -1.80583026]
 [-0.15964445 -0.12598816]
 [ 1.80521037  1.55385394]
 [-1.14207187 -1.13389342]
 [ 0.42981199  0.54594868]
 [-0.55261542 -0.46195658]
 [ 0.03684103  0.20998026]
 [ 0.82278296  0.8819171 ]
 [-0.7491009  -0.797925  ]]
[[-1.9280138  -2.14179868]
 [ 1.41223941  1.21788552]
 [ 1.01926844  0.8819171 ]
 [-1.73152832 -1.80583026]]


In [40]:
model = KNeighborsClassifier()

param_distributions = {
    "n_neighbors" : [3,4,5,6,6,7,7,8,2] 
   
}
randomsearch = RandomizedSearchCV(
    estimator = model,
    param_distributions = param_distributions,
    n_iter = 4,
    cv = 5,
    scoring = "accuracy"
)
randomsearch.fit( xtrainscaled,y_train)
print("best parameter:",randomsearch.best_params_)
print("best score:",randomsearch.best_score_)
print("best model:",randomsearch.best_estimator_)

    

C:\Users\Atul kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(


best parameter: {'n_neighbors': 3}
best score: 0.8833333333333334
best model: KNeighborsClassifier(n_neighbors=3)


In [42]:
# 1. Model ko train karein
model.fit(xtrainscaled, y_train)

# 2. Prediction hamesha TEST data (scaled) par karein, train par nahi!
# Note: Agar aapke test scaled variable ka naam alag hai (jaise xtestscaled), toh wo likhein
y_predict = model.predict(xtestscaled) 

# 3. Ab sabka length same ho jayega (Kyunki sab ab Test data hain)
comparsion = pd.DataFrame({
    "age" : x_test["age"].values,
    "study_hours" : x_test["study_hours"].values,
    "target" : y_test.values,
    "predictionvalues" : y_predict
})

# 4. Result dekhein
print(comparsion)

   age  study_hours  target  predictionvalues
0   18            1       0                 1
1   35           11       1                 1
2   33           10       1                 1
3   19            2       0                 1


In [45]:
accuracy = accuracy_score(y_test,y_predict)
print(accuracy)
print(classification_report(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))

0.5
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.50      1.00      0.67         2

    accuracy                           0.50         4
   macro avg       0.25      0.50      0.33         4
weighted avg       0.25      0.50      0.33         4

[[0 2]
 [0 2]]


C:\Users\Atul kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Atul kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Atul kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"

In [52]:
agen = input("enter a new age =")
studyhour = input("enter a study hours =")

newset = pd.DataFrame({
    "age" : [agen],
    "study_hours" : [studyhour]
})
print(newset)



enter a new age = 87
enter a study hours = 7


  age study_hours
0  87           7


In [53]:
newscaled = scaler.transform(newset)

prediction = model.predict(newscaled)

if prediction[0] == 1:
    print("PASS")
else:
    print("FAIL")

PASS
